# Generated by Django 2.0.7 on 2018-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imgURL',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='txt', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.CharField(default='anon', max_length=50),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
