# Generated by Django 2.0.7 on 2018-08-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180805_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vote',
            new_name='votes',
        ),
    ]
