# Generated by Django 2.0.7 on 2018-08-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20180807_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='postedBy',
        ),
    ]
