# Generated by Django 2.0.7 on 2018-08-09 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0010_auto_20180807_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentDownvotes',
            field=models.ManyToManyField(related_name='commentDownvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentUpvotes',
            field=models.ManyToManyField(related_name='commentUpvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(related_name='postDownvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(related_name='postUpvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
